# Generated by Django 4.1.1 on 2023-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_settings_client_clientlogo_client_taxnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('dar es salaam', 'DAR'), ('Arusha', 'Arusha'), ('Dodoma', 'Dodoma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('tsh', 'TZS'), ('$', 'USD')], default='R', max_length=100),
        ),
    ]
